// Modules/Tag/Resources/assets/js/components/DemoComponent.vue
<template>
    <div class="vue-demo-wrapper">
        <h1>Welcome to Vue with Vite in Tag Module!</h1>
        <p>
            To get started, edit
            <code>Modules/Tag/Resources/assets/js/registerVueComponents.js</code> and save to
            reload.
        </p>
        <div class="text-center">
            <p>Count: {{ count }}</p>
            <button class="btn btn-sm btn-primary" @click.prevent="increase">Increase</button>
            <button class="btn btn-sm btn-primary ms-2" @click.prevent="decrease">Decrease</button>
        </div>
    </div>
</template>

<script>
export default {
    name: "DemoComponent",
    data(){
        return {
            count: 0
        }
    },
    methods: {
        increase(){
            this.count++
        },
        decrease(){
            this.count--
        },
    }
}
</script>

<style scoped lang="scss">
.vue-demo-wrapper{
    background-color: rgba(0, 0, 255, 0.10);
    padding: 20px;
}
</style>

// Modules/Tag/Resources/assets/js/components/DemoComponent.jsx
import React, {useState} from "react";
import {createRoot} from "react-dom/client";

export default function DemoComponent() {
    const [count, setCount] = useState(0)

    const increase = () => {
        setCount(prev => prev + 1)
    }

    const decrease = () => {
        setCount(prev => prev - 1)
    }

    return (
        <>
            <h1>Welcome to React with Vite in Tag Module!</h1>
            <p>
                To get started, edit{" "}
                <code>Modules/Tag/Resources/assets/js/registerReactComponents.js</code> and save to
                reload.
            </p>

            <div className="text-center">
                <p>Count: {count}</p>
                <button className="btn btn-sm btn-primary" onClick={increase}>Increase</button>
                <button className="btn btn-sm btn-primary ms-2" onClick={decrease}>Decrease</button>
            </div>
        </>
    );
}

if (document.getElementById("reactRoot")) {
    const root = createRoot(document.getElementById("reactRoot"));
    root.render(<DemoComponent/>);
}
